---
layout: page
title: "Lesson Contents"
output: html_document
bibliography: references.bib
---


This page will give an overview of episodes within this tutorial and learning objectives accomplished in each. It will correspond to the computing skills checklist used in the course.

## Core Chapters

#### Chapter 1. Navigating your computer

- Files and directories
  - home directory
  - working directory
  - use the terminal in R studio to:
      - navigate
      - create and delete files
      - rename files
  - Manual download of data from NEON and save to a class folder
- Programs
  - programs are files written in executable code
  - we will learn to write small "programs" called "scripts"
    - you can write programs to automate tasks
    - you can write programs to make your scientific analyses reproducible
    
- Get R and RStudio set up on your computer with the student workbook
  - describe the different windows in RStudio: today just working files and terminal

**Learning Objectives**

In this lesson we will:

- describe the structure of a computer's file system
- use a command line interface to navigate the file system
- describe the relationship between R and RStudio (an IDE)
- set up an RStudio project


**Computational Skills**

In this lesson students will learn to use a Unix terminal to:

1. navigate between directories
2. view files in a directory
3. make, delete, rename and move files


#### Chapter 2. Intro to R and RStudio

*from:* [@swc-reproducible-lesson](https://swcarpentry.github.io/r-novice-gapminder/) episodes 1, 2, 3

- R is a programming language
- RStudio is an IDE
  - various additional functionality of RStudio
- R can:
  - do computations
  - manipulate data
  - access files on your computer or the internet
  - make graphs
  - create documents
  - create apps
  - almost anything... though it is not always the best tool for every job.
- Why R?
  - R has a wide user community and will always be free
    - user contributed packages:
      -NEONUtilities
  - R and RStudio make it easy for anyone to reproduce your scientific analyses
  - It is (relatively) easy to get help with (almost) anything

**Learning Objectives**

In this lesson we will:

- discover why so many scientists use R
- describe the contents of the windows in an RStudio session
- use the console for mathematical calculations
- state the rules for assigning variables
- work with vectors
- write and save a code script in a project folder
- read and view tabular data from a file
- learn how to get help and troubleshoot error messages
- install and load packages in R


**Computational Skills**

In this lesson students will learn to use R and RStudio to:

1. execute simple mathematical calculations
2. assign and manipulate variables
3. assign, subset and manipulate data in a vector
4. execute vector algebra
5. write and save a code script
6. write comments in a code script
7. read a data table from a file
8. access and understand a function's documentation page



#### Chapter 3. Data organization in spreadsheets

*from:* [@dc-spreadsheet-lesson](https://datacarpentry.org/spreadsheet-ecology-lesson/)

- Best practices in data table formatting
  - tidy tables
  - missing data
  - dates
  - text-based and avoids special characters
  - raw data vs. derived data and README files
- Spreadsheet program quality control features
- Data export from spreadsheet programs
- Text-based data tables: delimited formats
  - typical delimiter characters
  - white space characters: space, tab, new line
- Metadata

**Learning Objectives**

In this lesson we will:

- describe best practices in working with data tables
- understand the structure of a text-based data table file
- use metadata to understand the contents of a data table
- utilize quality control features of spreadsheet software to generate clean data

**Computational Skills**

In this lesson students will learn to:

1. follow best practices in formatting data tables
2. document steps of a data analysis using metadata and a README file
3. import and export text-based data tables using spreadsheet software


#### Chapter 4. R: Data structures and operations

*from:* [@swc-reproducible-lesson](https://swcarpentry.github.io/r-novice-gapminder/) episodes 4, 5, 6, 11

- Basic data types in R
  - vectors vs. lists
  - multidimensional arrays
  - dataframes vs. matrices
  - data types: numeric, character, factor, logical
- Manipulating data frames
- Subsetting vectors and data frames


**Learning Objectives**

In this lesson we will:

- describe the main data structures and types in R
- manipulate and extract values from data frames using base R


**Computational Skills**

In this R lesson students will learn to:

1. differentiate between vectors, arrays, lists and data frames
2. differentiate between numeric, character, factor and logical data types
3. view the structure and class of an object
4. subset data frames and vectors
5. write logical test expressions using `==`,`!=`, `>`, `<`, and `%in%` 

#### Chapter 5. R: Vectorization and functions

*from:* [@swc-reproducible-lesson](https://swcarpentry.github.io/r-novice-gapminder/) episodes 9, 10


- NEON Utilities functions & reading a function help file

**Learning Objectives**

In this lesson we will:

- describe what vectorized functions are and how to use them
- explain how functions work and define and our own functions
- explain why we should divide programs into small single-purpose functions


**Computational Skills**

In this lesson students will learn to use R to:

1. define and use a function with multiple arguments
2. define default values for function arguments
3. write checks on argument conditions within a function
4. differentiate between missing values (`NA`) and empty values (`NULL`)
5. source code from a script


#### Chapter 6. R: Simple graphs with ggplot2

*from:* [@swc-reproducible-lesson](https://swcarpentry.github.io/r-novice-gapminder/) episode 8


**Learning Objectives**

In this lesson we will:

- use ggplot2 to generate single-panel graphics with one data layer and one statistic layer
- manipulate the aesthetics of a plot using different colors, shapes, and lines
- use different geometries to change the way data is displayed in a plot


**Computational Skills**

In this lesson students will learn to use the ggplot2 packaged in R to:

1. create a scatter plot with a linear regression line
2. create a line graph
3. create a bar chart with error bars
4. create a stacked bar chart
5. map aesthetics to data values
6. write axis labels with mathematical notation


#### Chapter 7. R: Controlling program flow

*from:* [@swc-reproducible-lesson](https://swcarpentry.github.io/r-novice-gapminder/) episode 7


**Learning Objectives**

In this lesson we will:

- use conditional statements to make data-dependent decisions
- use loops to repeat things
- write expressions containing multiple logical statements

**Computational Skills**

In this lesson students will learn to use R to:

1. executes if-else statements
2. repeat steps using for and while loops
4. evaluate expressions using `&` ('and') and `|` ('or')


#### Chapter 8. R: Complex graphs with ggplot2

*from:* [@swc-reproducible-lesson](https://swcarpentry.github.io/r-novice-gapminder/) episode 8

**Learning Objectives**

In this lesson we will:

- use ggplot2 to create multi-panel graphics with multiple data layers
- learn how position scales control the way axes are displayed
- learn how themes control the way plots are displayed
- use inclusive color palettes that are visible to people with impaired  color vision
- change the default labels in a legend
- add reference lines to a plot

**Computational Skills**

In this lesson students will learn to use the ggplot2 package in R to:

1. use facets to display data in separate panels of a graph
2. add multiple data layers to a plot and change the order in which they are layered
3. change the scale, limits and breaks on an axis
4. change the default fonts, colors, and sizes using a theme
5. change a discrete and continuous color scale
6. change the text labels in a legend
7. add horizontal and vertical reference lines to a plot



#### Chapter 9. R: Data manipulation in the tidyverse

*from:* [@swc-reproducible-lesson](https://swcarpentry.github.io/r-novice-gapminder/) episodes 13 and 14

**Learning Objectives**

In this lesson we will:

- differentiate between "longer" and "wider" data and explore when to use each format
- use functions in the dplyr and tidyr R packages to combine, subset, summarize and change the layout of data frames
- write multistep data manipulations by composing functions together with pipes


**Computational Skills**

In this lesson students will learn to use R to:

1. `join` two tables using a key
2. `select` columns from a table using matching criteria
3. `filter` rows from a table
4. create new columns using `mutate`
5. use `group_by` with `summarize` to calculate summary statistics across factors
6. use `pivot` functions from the tidyr package to change the format of a table from long to wide or wide to long
7. use pipes (`%>%`) to compose functions


## Additional Chapters

#### Chapter A. Producing reports with Rmd and knitr

*from:* [@swc-reproducible-lesson](https://swcarpentry.github.io/r-novice-gapminder/) episode 15


#### Chapter B. R: Intro to geospatial raster data

*from:* [@dc-semester-biology](https://datacarpentry.org/semester-biology/) Spatial Data 1 lesson


#### Chapter C. Data cleaning with OpenRefine

Complete the episodes in: (Data Cleaning with OpenRefine for Ecologists)[http://datacarpentry.org/OpenRefine-ecology-lesson/]


## References


