---
layout: page
title: "Setting up your computer"
output: html_document
---

## R and RStudio

**R** and **RStudio** are separate downloads and installations. R is the underlying statistical computing environment, but using R alone is tricky for beginners. RStudio is a graphical integrated development environment (IDE) that makes using R much easier and more interactive. You need to install R before you install RStudio. In the sections below are the instructions for installing R and R Studio on your operating system.

### If you don't have R installed

If you have never used R or RStudio on your computer, then you probably don't have R installed.

1. Visit the [CRAN website](https://cran.r-project.org/){target="_blank"}
2. In the first box labeled "Download and Install R", click on the link for the operating system on your computer (e.g. Windows, Mac or Linux)

#### R for Windows

1. Click "base". Then on the next page, click "Download R.x.x.x for Windows" (x.x.x are the version number)
2. Save the `.exe` file to a location on your computer (e.g. the Downloads folder).
3. Open and run the `.exe` file you just downloaded. This will install and set up R on your computer.

#### R for Mac

1. Click on the `.pkg` file for the latest R version that will work on your computer.
2. Save this file somewhere on your computer (e.g. Downloads)
3. Open the downloaded `.pkg` file to install R
4. It is also a good idea to install [XQuartz](https://www.xquartz.org/){target="_blank"}. Follow the installation instructions on that website. R will work without XQuartz, but you may find that you need it later if certain packages do not install properly.
  
#### R for Linux
 
1. Choose your distribution of Linux.
2. Follow the instructions on the website.

#### RStudio for all operating systems

1. Go to the [RStudio download page](https://www.rstudio.com/products/rstudio/download/#download){target="_blank"}
2. The website should automatically detect your operating system and provide the correct installer download as a large button. If you need a different version, scroll down the page and select the installer download that matches your operating system.
3. Save the file somewhere on your computer (e.g. Downloads).
4. Open the downloaded file to launch the RStudio installer and follow the instructions in the prompts.
5. Once it is installed, open RStudio to make sure it works and you don't get any
  error messages.

### If you do have R and RStudio installed

* Open RStudio, and click on "Help" > "Check for updates". If a new version is
	available, quit RStudio, and download the latest version for RStudio.
* To check which version of R you are using, start RStudio and the first thing
  that appears in the console indicates the version of R you are
  running. Alternatively, you can type `sessionInfo()`, which will also display
  which version of R you are running. Go on
  the [CRAN website](https://cran.r-project.org/){target="_blank"} and check
  whether a more recent version is available. If so, please download and install
  it. You can [check here](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-UNinstall-R_003f){target="_blank"} for more information on how to remove old versions from your system if you wish to do so.

## Course Workbook


1. Download the Student Workbook from [here](workbook/R-course-NEON-workbook.zip). Save this zipped file in the folder where you are saving work for this course.
2. Unzip the folder you downloaded. The name of the folder that you unzip should be R-course-NEON-workbook. Instructions for how to unzip folders are located [here for Mac](https://support.apple.com/guide/mac-help/zip-and-unzip-files-and-folders-on-mac-mchlp2528/){target="_blank"} and [here for Windows](https://support.microsoft.com/en-us/windows/zip-and-unzip-files-f6dde0a7-0fec-8294-e1d3-703ed85e7ebc){target="_blank"}.


<!-- May introduce Git in a subsequent version of this course

***

### Git

#### Windows

1. Download the git installer for Windows [here](https://git-for-windows.github.io/). This will install bash, which is a command-line shell program for interacting with files and programs on your computer.
2. Run the installer that you just downloaded. Click "Next" as needed and when you get to the following options make sure that you:
    + Select "Use Git from the Windows Command Prompt". 
    + Keep "Checkout Windows-style, commit Unix-style line endings" selected.
    + Select "Use Windows' default console window".
    + If you forgot to do any of these, rerun the installer and select the appropriate options.
3. That's it! You should now have three new programs installed in a folder called Git under your Program Files.

#### macOS

Follow the instructions below or view this [video tutorial](https://www.youtube.com/watch?v=9LQhwETCdwY).

1. Go to [this list](https://sourceforge.net/projects/git-osx-installer/files/) and download an installer for Git.
    + If you are using OS X 10.9 and higher, choose the most recent version for "mavericks".
    + If you are using an earlier version of OS X, choose the most recent version for "snow leopard".
2. Run the installer you downloaded.
3. After installing Git, there will not be anything in your /Applications folder, because Git is a command line program.

Note: if you have OSX El Capitan you may experience some errors when running Git if you don't have an updated XCODE. [Here](https://stackoverflow.com/questions/32893412/command-line-tools-not-working-os-x-el-capitan-macos-sierra) is a description of the issue on StackOverflow and the solution is to open a Terminal window and type `xcode-select --install`.

#### Linux

You may already have Git installed. If not, you can try to install it via your distro’s package manager. For Debian/Ubuntu run `sudo apt-get install git` and for Fedora run `sudo yum install git`.

***
-->

