---
title: "Introduction to Computing in R with NEON"
author: Jes Coyle
institution: Saint Mary's College of California
output: html_document
---

## Overview
This is a self-paced tutorial adapted from [Data Carpentry](http://datacarpentry.org/) and [Software Carpentry](http://software-carpentry.org/) that teaches biologists basic data science and computing skills using  [National Ecological Observation Network](http://neonscience.org) data. It is being developed for use in an upper division Biology course at Saint Mary's College of California beginning in August 2023. **These materials are not currently ready for use.**


## Organization

### How to use this tutorial

This book is organized into sequential chapters with content that builds on prior chapters. Learners who have no prior experience with R should start with chapter 1 and progress through the book sequentially.

Access the chapters using the menu bar at the top of the website. Each chapter begins with an overview page that introduces the learning goals and important terms your will gain by working through the lesson. The Lesson tab for each chapter contains step-by-step instructions. Read through the lesson while running examples of code in RStudio on your own computer. Be sure to complete all of the challenges, as the contents of each challenge in the lessons build upon one another. Use the Exercises tab to practice the skills gained during the lesson. Most lessons were adapted from other sources- these are listed in the References tab along with other useful resources for readers wanting to learn more.


### Where is everything?

The menu at the top of this website provides access to everything you need.

* [Home](index.hmtl) takes you to this page.
* [Computer Setup](computer-setup.html) describes how to get you computer ready to work through the lessons.
* [NEON Data](NEON-data-intro.html) describes the National Ecological Observatory Network and which data products are used in the lessons.
* The Chapters dropdown menu provides access to each lesson as well as an [overview](00-module-contents.html) of the contents of each lesson.
* [Exercises](exercises-guide.html) provides links to download exercise files that accompany each lesson.
* [RStudio Workbook](download-student-RStudo-project.html) provides a link to download an RStudio project that accompanies these lessons.


## Get Started

### Computer set-up

This course requires you to have certain software installed on your computer. Follow the instructions on the [Computer Setup](computer-setup.html) to learn how to install this software before downloading the workbook.

### Student workbook

The student workbook is a zipped folder that contains a folder with data files necessary for completing the lessons. It also contains a folder with exercise files that accompany each lesson. Follow the instructions on the [Computer Setup](computer-setup.html) page to download the workbook.

## Open Educational Resource

These materials will be published open access, but they are **(not currently ready for use or adaptation.**

### Acknowledgements
Thank you to [Data Carpentry](http://datacarpentry.org/) and [Software Carpentry](http://software-carpentry.org/) for providing open and remixable materials for scientists learning programming and data science. This course draws heavily from the [Data Carpentry for Biologists](https://datacarpentry.org/semester-biology/) and [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/).
