# These settings control the behavior of all chunks in the novice R materials.
# For example, to generate the lessons with all the output hidden, simply change
# `results` from "markup" to "hide".
# For more information on available chunk options, see
# http://yihui.name/knitr/options#chunk_options

library("knitr")

## We set the path for the figures globally below, so if we want to
## customize it for individual episodes, we can append a prefix to the
## global path. For instance, if we call knitr_fig_path("01-") in the
## first episode of the lesson, it will generate the figures in
## `fig/rmd-01-`
knitr_fig_path <- function(prefix) {
    new_path <- paste0(opts_chunk$get("fig.path"),
                      prefix)
    opts_chunk$set(fig.path = new_path)
}

## We use the rmd- prefix for the figures generated by the lessons so
## they can be easily identified and deleted by `make clean-rmd`.  The
## working directory when the lessons are generated is the root so the
## figures need to be saved in fig/, but when the site is generated,
## the episodes will be one level down. We fix the path using the
## `fig.process` option.

opts_chunk$set(error = TRUE, tidy = FALSE, results = "markup", comment = NA,
               fig.align = "center", fig.path = "images/rmd-",
               fig.width = 8.5, fig.height = 8.5,
               fig.retina = 2)



### Custom hooks to make answers fold up 

## For code to be evaluated in an answer
## Use: ```{r, answer = TRUE}
knitr::knit_hooks$set(answer = function(before, options, envir) {
  if (before) {
    paste(
      "<div class=\"accordion\">",
      "<h4 class=\"toc-ignore\">Answer</h4>",
      "<div style=\"background: #fff;\">",  sep = "\n")
  } else {
    paste("</div>", "</div>", sep = "\n")
  }
})


## For text-only answers
## Use: ```{text_answer, echo = FALSE}
eng_text_answer <- knitr:::eng_html_asset(
  paste(
    "<div class=\"accordion\">",
    "<h4 class=\"toc-ignore\">Answer</h4>",
    "<div style=\"background: #fff;\">",
    "<p>",  sep = "\n"),
  paste(
    "</div>", "</div>", "</p>", sep = "\n"
  )
)

knitr::knit_engines$set(text_answer = eng_text_answer)


# NOT USED - SAVED IN CASE NEEDED LATER
# # The hooks below add html tags to the code chunks and their output so that they
# # are properly formatted when the site is built.
# 
# hook_in <- function(x, options) {
#   lg <- tolower(options$engine)
#   style <- paste0(".language-", lg)
# 
#   stringr::str_c("\n\n~~~\n",
#     paste0(x, collapse="\n"),
#     "\n~~~\n{: ", style, "}\n\n")
# }
# 
# hook_out <- function(x, options) {
#   x <- gsub("\n$", "", x)
#   stringr::str_c("\n\n~~~\n",
#     paste0(x, collapse="\n"),
#     "\n~~~\n{: .output}\n\n")
# }
# 
# hook_error <- function(x, options) {
#   x <- gsub("\n$", "", x)
#   stringr::str_c("\n\n~~~\n",
#     paste0(x, collapse="\n"),
#     "\n~~~\n{: .error}\n\n")
# }
# 
# hook_warning <- function(x, options) {
#   x <- gsub("\n$", "", x)
#   stringr::str_c("\n\n~~~\n",
#     paste0(x, collapse = "\n"),
#     "\n~~~\n{: .warning}\n\n")
# }
# 
# knit_hooks$set(source = hook_in, output = hook_out, warning = hook_warning,
#   error = hook_error, message = hook_out)
